### ISSUE TITLE
Allow the possibility to create separated slave nodes.

### ISSUE THREAD

**Issue by acautin** [K2InformaticsGmbH/oranif#42] opened 2019-05-10 12:02 UTC
It is possible the user of the library wants to have isolated environments for connections that are not related.

**Comment by stoch** [comment] 2019-05-10 14:03
This means that the prefix of the slave node should be configured in the cpro job config (atom or binstr or string according to current standards).

Ultimately, a value like atom 'undefined' could mean that the driver should be called directly, without slave node (for performance optimisation/comparison with associated risk taken).

**Comment by c-bik** [comment] 2019-05-23 13:14
Duplicate of #43

**Closed by c-bik** 2019-05-23 13:14 UTC
Labels: enhancement

**Comment by c-bik** [comment] 2019-05-23 13:16
> This means that the prefix of the slave node should be configured in the cpro job config (atom or binstr or string according to current standards).
> 
> Ultimately, a value like atom 'undefined' could mean that the driver should be called directly, without slave node (for performance optimisation/comparison with associated risk taken).

`cproJob` table will ONLY support `atom` for slave node name configuration!
